/*
 * generated by Xtext 2.15.0
 */
package org.monacoex.dsl.monascript


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LanguageStandaloneSetup extends LanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new LanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
