/*
 * generated by Xtext 2.15.0
 */
package org.monacoex.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MonascriptsRuntimeModule extends AbstractMonascriptsRuntimeModule {
}
