/*
 * generated by Xtext 2.15.0
 */
package org.monacoex.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MonascriptsStandaloneSetup extends MonascriptsStandaloneSetupGenerated {

	def static void doSetup() {
		new MonascriptsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
